### ISSUE TITLE
Incorrect processing of -o flag

### ISSUE THREAD

**Issue by fedosgad** [Nekhaevalex/TD4-Assembler#1]
When in disassembly mode, -o flag works as it would work in compile mode.
For example, after running
`./TD4_asm -c test.s -o test`
`./TD4_asm -d test -o test_dis.s`
test_dis.s will contain binary program code and not disassembled listing.
Proposals: either prohibit usage of -d and -o simultaneously or output assembly listing in file specified.

**Comment by Nekhaevalex** [comment]
Will be fixed in v3.0
